### ISSUE TITLE
Could you share the training details on Posetrack 18?

### ISSUE THREAD

**Issue by Odaimoko** [mks0601/TF-SimpleHumanPose#10]
I am sorry that I ask this question because I barely know tf. Could you pls describe what you have done and what parameters you use during training? Did you follow the training technique used on posetrack 17 in the original paper?

**Comment by mks0601** [comment]
Hi, I added detailed explanation in README like below.

After training model on the COCO dataset, I set `lr`, `lr_dec_epoch`, `end_epoch` in `config.py` to `5e-5`, `[150, 155]`, `160`, respectively. Then, run `python train.py --gpu $GPUS --continue`.

**Comment by Odaimoko** [comment]
Thank you very much. Did you also train on posetrack 17?

**Comment by mks0601** [comment]
Unfortunately, no. You can try by changing my code.
