### ISSUE TITLE
Some confusion about the repo

### ISSUE THREAD

**Issue by laowangFish** [mks0601/TF-SimpleHumanPose#11]
Thank you for your work. You are very cool. I have watched your two projects. There are some questions about this repo. Does this repo only implement the 2d human pose estimation with bboxs already in place. The Simple-Baseline paper has a lot of stuff about detector bbox and propagate bbox processing, optical flow tracking and so on. The original repo and yours don't seems to cover that .  So the algorithm of tracking processing implementation is not open source?

**Comment by mks0601** [comment]
Hi, thanks for having interests in my projects. I only implemented frame-based 2D multi-person pose estimation part without tracking part. You can check other repos for tracking part :)

**Comment by Tobias-Fischer** [comment]
Hi @mks0601, thanks for your work! Do you know of any repos where the tracking part is implemented?

**Comment by mks0601** [comment]
@Tobias-Fischer Sorry, I do not know :(

**Comment by Tobias-Fischer** [comment]
No problem, thanks for letting me know!

**Comment by thiranjayamunasinghe** [comment]
@Tobias-Fischer Hey, did you find any implementations of the tracking part?
