### ISSUE TITLE
Pre-Trained Model for resnet_152 ?

### ISSUE THREAD

**Issue by Abby263** [mks0601/TF-SimpleHumanPose#12]
Do you have the pre-trained model for Resnet_152 ?

**Comment by mks0601** [comment]
Hi, I received your mail. Sorry for late reply. I am currently busy :( 
I haven't train resnet 152 model. Sorry.

**Comment by bbudescu** [comment]
Obtaining a frozen tensorflow graph from the tensorflow model can be achieved using ONNX. However, I'm not quite sure how to load the weights into the model instantiated by this code. I guess there would be some naming differences between the variables generated by the convertors (pytorch->onnx&onnx->tensorflow) and the variables defined in this code. Did you ever try this approach?

Note: I'd like to use the code in this repo to further customize the model, which I can't do with the frozen graph, and only partially load the pre-trained weights.

**Comment by falcon60** [comment]
@bbudescu I tried converting PyTorch to ONNX and then ONNX to Tensorflow using [onnx_tf](https://github.com/onnx/onnx-tensorflow/tree/master/onnx_tf) . Successfully exported the model to ONNX with opset version set as 11 (as the UpSample implementation used in this model is not supported below opset 11). Failed to convert to Tensorflow as [onnx_tf](https://github.com/onnx/onnx-tensorflow/tree/master/onnx_tf) has not yet implemented Conv layer for opset 11.
