### ISSUE TITLE
Transfer Learning on Custom Data

### ISSUE THREAD

**Issue by Abby263** [mks0601/TF-SimpleHumanPose#14]
Hey, 
Thanks for the pre-trained models.
I want to do transfer learning on top of that on my Custom Dataset.
I have the Custom training images tagged in COCO format and saved in json Format.
Can you please guide on how to go ahead from here ?

**Comment by mks0601** [comment]
I cannot understand what you are asking for. Can you ask me more specifically?

**Comment by wingedrasengan927** [comment]
Are there pre-trained models on coco or mpii datasets?

**Comment by mks0601** [comment]
you can download pre-trained model on the coco dataset in readme

**Comment by wingedrasengan927** [comment]
Yes. Found it. Thank you so much.
