### ISSUE TITLE
tf.stop_gradient

### ISSUE THREAD

**Issue by soldierofhell** [mks0601/TF-SimpleHumanPose#18]
Hi,

Could someone explain why do we need tf.stop_gradient applied to gt_heatmap. I mean this line from model.py:
`gt_heatmap = tf.stop_gradient(self.render_gaussian_heatmap(target_coord, cfg.output_shape, cfg.sigma))`

I don't see any dependency on tf.Variables in render_gaussian_heatmap() graph?

**Comment by mks0601** [comment]
You are right. In the initial implementation, I tested some modules when rendering gaussian heatmap. Now, you can just remove stop_gradient.

**Comment by soldierofhell** [comment]
Thanks for the confirmation
