### ISSUE TITLE
tfflat

### ISSUE THREAD

**Issue by soldierofhell** [mks0601/TF-SimpleHumanPose#19]
Hi,
I wonder who's the author of tfflat modules. It's another repo that I see similar code. It reminds me a bit of tensorpack style, but simpler. Is it a part of some general library for training? Just curious

Regards,

**Comment by mks0601** [comment]
Hi, the tfflat part is from https://github.com/chenyilun95/tf-cpn as I wrote in the README. I modified it to more simple version.

**Comment by soldierofhell** [comment]
I suspect this may be a piece of some internal code from Megvii because I saw it in some of their repos. Nevermind :)
