### ISSUE TITLE
name of output tensor

### ISSUE THREAD

**Issue by ZyadShokry** [mks0601/TF-SimpleHumanPose#22]

**Comment by ZyadShokry** [comment]
Sorry for this naive question but it is critical: What is the name of the output tensor of COCO Model?

**Comment by mks0601** [comment]
what do you mean by the name of output tensor? There is no dataset specific variable in train.py and test.py

**Comment by ZyadShokry** [comment]
for inference using .pb graph file, one needs to know the output node name... the graph has a clear input node: tower0/Placeholder, but i am confused what is the appropriate output node ( I thought it is tower0/out/Conv2D but results infer that i'm wrong)

**Comment by jackytu256** [comment]
just guess the name of output tensor should be "tower_0/out/BiasAdd:0"
