### ISSUE TITLE
TypeError: Can't instantiate abstract class Tester with abstract methods _make_data

### ISSUE THREAD

**Issue by Marshall0304** [mks0601/TF-SimpleHumanPose#23]
hello, i want to use your code to inference single image, and i followed the code in test.py, but, when i use tester = Tester(Model(), cfg), i got this error:
TypeError: Can't instantiate abstract class Tester with abstract methods _make_data
do u know why and how can i repair this bug? thanks

**Comment by mks0601** [comment]
Can you tell me what did you change in a more detailed way? Although the `Tester` class inherits `Base` class, it does not call _make_data method.
