### ISSUE TITLE
CPU only support

### ISSUE THREAD

**Issue by tucan9389** [mks0601/TF-SimpleHumanPose#24]
안녕하세요. 한국인인듯하여 한국어로 질문을 드립니다.

이 프로젝트를 macOS에서 돌려보기 위해서 시도해보고 있는데 어려움을 겪고 있습니다. 그래서 몇가지 질문을 드립니다.
1. cpu only 환경은 고려하지 않은 프로젝트인가요?
2. cpu only가 고려되지 않은 프로젝트라면 cpu only 환경에서 실행가능하게 기능을 추가하여 PR을 날려도 될까요?

감사합니다 :-)

**Comment by mks0601** [comment]
안녕하세요 

CPU환경은 고려하지 않은 코드입니다. 
PR을 하셔도 되는데, 제가 검토해보고 기존 코드의 pipeline을 크게 해치지 않는다면 반영하도록 하겠습니다.

안녕히 계세요
경식 드림

--
Gyeongsik Moon
Ph.D. Candidate
Department of ECE, SNU, Seoul, Korea
https://mks0601.github.io <https://mks0601.github.io/>

**Comment by tucan9389** [comment]
감사합니다. 질문사항이 생기면 여기 이슈에 남기기 위해서 이슈는 닫지 않겠습니다.

**Comment by khan958** [comment]
@tucan9389 Is it possible that we can run this code at CPU. Need your suggestion Plz.

**Comment by mks0601** [comment]
I haven't tested this code under CPU-only environment :(
