### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'tmp_result_0.pkl'

### ISSUE THREAD

**Issue by Emma0928** [mks0601/TF-SimpleHumanPose#27]
When the model on MPII has been trained by one GPU, I want to use test.py to evaluation  the result. The error about some pkl files occurs while I didn't find any such files. 
![Screenshot from 2019-06-06 15-46-231](https://user-images.githubusercontent.com/40055478/59016159-3b5bcf80-8873-11e9-83ec-2ebf34912203.png)

**Comment by mks0601** [comment]
The `tmp_result_0.pkl` is temporal output file which does not need to be prepared. For the MPII dataset, I did not implemented testing data loading part. Maybe you can implement it by modifying `dataset.py`

**Comment by anhminh3105** [comment]
Hello, I am getting the same error when trying to run test.py with the 140 pre-trained epoch resnet50-coco model. Do you have any idea?
