### ISSUE TITLE
When should I stop training?

### ISSUE THREAD

**Issue by vacing** [mks0601/TF-SimpleHumanPose#3]
If there are some other indicators to tell me when to stop except epoch loss?
The epoch loss changes heavily and it's hard to determine if the model converged or not

**Comment by mks0601** [comment]
You have to run full epoch to achieve final performance. If you stop earlier, accuracy would be lower than that of README. I tested performance of earlier epochs when I was implementing this repo. At 10th epoch, it achieved about 55 mAP.
