### ISSUE TITLE
Why is Encoder part trainable True?

### ISSUE THREAD

**Issue by YongGeunLee** [mks0601/TF-SimpleHumanPose#31]
In the original paper, the encoder part is freezing. Is there a reason why you chose the trainable "True" in the encoder(ResNet50) of the code?
Thanks.

**Comment by YongGeunLee** [comment]
In addition, is there a reason why head_net(Decoder part) did not use batch normalization differently than the original paper? Was it better if you didn't use it?

**Comment by mks0601** [comment]
Are you sure encoder part of the original paper is frozen?

**Comment by YongGeunLee** [comment]
I misunderstood. Because there was no connection between the decoder part and the encoder part, such as U-net or Hourglass network, I misunderstood training methods with encoder part frozen. I will close issue. Thank you for your quick reply.
