### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'tmp_result_0.pkl' and IndexError: list index out of range

### ISSUE THREAD

**Issue by anhminh3105** [mks0601/TF-SimpleHumanPose#36]
Hello,

I am trying to run the test.py on the provided pre-trained model 256x192_resnet50_coco but I am getting the following errors:
![Screenshot from 2019-07-22 17-02-53](https://user-images.githubusercontent.com/18170028/61638707-9f5f1980-aca2-11e9-9840-d3106e2d0812.png)
though I don't really understand what it does yet, I skimmed over the code and you seemed to try to delete it. So as I don't have that pickle file, I tried to bypass those blocks of code by setting argument `dump_method=2` in `test.py` like so ```MultiGPUFunc = MultiProc(len(args.gpu_ids.split(',')), func, dump_method=2)``` but then I encountered another error as following:
![Screenshot from 2019-07-22 17-11-45](https://user-images.githubusercontent.com/18170028/61639283-de419f00-aca3-11e9-98cb-fa3b05ee6d7a.png)
the command I used to run the programme is : ```python test.py --gpu 0 --test_epoch 140``` as I have only 1 gpu card. Also I tried to changed argument `gpu` to 1, 0-1 but the error is still the same.

As an aside,  I am not sure which file is right for the dets/human_detection.json and so I used the human_detection_test-dev2017.json of Human detection result on test-dev2017 (57.2 AP on human class) and renamed it to human_detection.json. I wonder if it is the cause to the error?

I need your help.

thanks in advance.

**Comment by mks0601** [comment]
The pickle file is a temporal file which is generated and deleted in testing stage. You don't have to prepare pickle files. Can you tell me which dataset are you using? The human detection result should be the one of dataset you want to use.

**Comment by mks0601** [comment]
I tested my code and it works in single GPU environment. I think your human detection file is not the same with your dataset.

**Comment by anhminh3105** [comment]
I am using the COCO dataset test2017, with annotations from image_info_test2017.zip.

Indeed I don't know where to download the `human_detection.json file`. Instead, I found the `human_detection_test-dev2017.json` file and I thought it might be it so I renamed it to `human_detection.json` and placed it under `data/COCO/dets/`.The link to that file is this one

![Annotation 2019-07-22 204147](https://user-images.githubusercontent.com/18170028/61653233-86666080-acc2-11e9-9ae3-e56bab659472.jpg)

**Comment by mks0601** [comment]
Did you change `val` in `config.py` as `test`?

**Comment by anhminh3105** [comment]
Ah yeah, no I didn't. I will try that as soon as I wake up tomorrow and let you know right then

**Comment by mks0601** [comment]
Yes. I'm sure that is the reason. Good night!

**Comment by anhminh3105** [comment]
I changed that and it works, it is indeed the reason. 

However, the APs and ARs outputs are all -1, maybe something is not right so I will try to create another issue.

Many thanks to you and your great supports, I'm very appreciated ^.^
