### ISSUE TITLE
test.py outputs -1 for Average Precision and Average Recall metrics

### ISSUE THREAD

**Issue by anhminh3105** [mks0601/TF-SimpleHumanPose#37]
I ran the `test.py` prorgramme on the **COCO test2017** dataset with the `human_detections_text-dev2017.json` renamed to `human_detections.json`. However, the output results of all the *Average Precision* and *Average Recall* metrics are -1. Here is the snapshot:

![Screenshot from 2019-07-23 11-05-01](https://user-images.githubusercontent.com/18170028/61694228-be5cba80-ad39-11e9-90ea-3fb129c081ce.png)

I am unsure whether the problem is due to the `human_detections_text-dev2017.json` is not the right file to use.

Could you please help? Thanks in advance.

**Comment by mks0601** [comment]
For the test set, COCO dataset does not provide groundtruth. You have to evaluate your result using CodaLab. Please read http://cocodataset.org/#guidelines

**Comment by anhminh3105** [comment]
Thanks for the guide.

I ran the test with **COCO val2017** dataset and reproduced the exact same results as you got. 

I will try to upload the test2017 dataset outputs to CodaLab to get the results next.

Thank you.
