### ISSUE TITLE
set v=1 of all keypoints when testing?

### ISSUE THREAD

**Issue by chenyanyin** [mks0601/TF-SimpleHumanPose#38]
hello, i am confused about test result. As we know, all keypoints  are composed 3 parts: (x,y,v), v is valid. but i found your test result(https://cv.snu.ac.kr/research/TF-SimpleHumanPose/COCO/pose_result/person_keypoints_256x192_resnet50_val2017_results.json), is all 1,  and test code,
![11111](https://user-images.githubusercontent.com/17922048/61990772-685d7f00-b079-11e9-8cd6-78c7128cf149.jpg)  

set v=1 of all keypoints.

**Comment by mks0601** [comment]
If you read http://cocodataset.org/#keypoints-eval, that does not matter.
