### ISSUE TITLE
 The result is strange

### ISSUE THREAD

**Issue by Yoonminsun** [mks0601/TF-SimpleHumanPose#39]
GPU 0: : 332683it [2:01:09, 28.82it/s]                                                                 dump to temp_file: tmp_result_0
tmp_result_0.pkl deleted.
Loading and preparing results...
DONE (t=14.31s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *keypoints*
DONE (t=38.31s).
Accumulating evaluation results...
DONE (t=1.45s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets= 20 ] = -1.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets= 20 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50      | area=   all | maxDets= 20 ] = -1.000
 Average Recall     (AR) @[ IoU=0.75      | area=   all | maxDets= 20 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] = -1.000

The result is weird and takes too long

**Comment by mks0601** [comment]
Hey you opened three issues in one day, which can be easily fixed by yourself. Please see closed issues and debug it before asking here. This is not a problem of my repo. Please read this issue.
https://github.com/mks0601/TF-SimpleHumanPose/issues/37
