### ISSUE TITLE
where can I get human_detection.json of MPII?

### ISSUE THREAD

**Issue by wangdong128** [mks0601/TF-SimpleHumanPose#4]
I want to test model trained from MPII, where can I get human_detection.json of MPII

**Comment by mks0601** [comment]
I implemented codes for MPII dataset, however did not train and test on that. You can convert MPII dataset using `tool/mpii2coco.py` to convert MPII dataset annotation files to COCO format and use detectron (https://github.com/facebookresearch/Detectron) to detect human. Since detectron uses coco format data, test it on the MPII dataset would be easy.

**Comment by wangdong128** [comment]
Thank you for your reply. And how about the human_detection.json of coco2017, can you provide it，thanks

**Comment by mks0601** [comment]
It is already uploaded. You can download it in the README.

**Comment by Emma0928** [comment]
Thanks for your work. I'm confused about human_detection.json file. Is this file just for human detection? You mean I can seek help from other works for human detection such as https://github.com/facebookresearch/Detectron? If I don't use this step, will it influence the test result?

**Comment by mks0601** [comment]
Of course you can use them. Note that you need to prepare coco 2017 dataset. As far as I know, Detectron has the result of coco 2014. However, as coco 2017 train == (coco 2014 trainval), and coco 2017 val == coco 2014 minival, you can easily convert their result to coco 2017 format.

**Comment by niazahamd89** [comment]
@mks0601 is it possible to implement your work on windows environment i tried but i am getting the error and i am stoked here can you sort my problem please? 

  ZMQError in socket.bind(). Perhaps you're                 using pipes on a non-local file system. See documentation of PrefetchDataZMQ for more information.
Traceback (most recent call last):
  File "train.py", line 30, in <module>
    trainer = Trainer(Model(), cfg)
  File "C:\Users\niaza\TF-SimpleHuman\main\..\lib\tfflat\base.py", line 194, in __init__
    self._data_iter, self.itr_per_epoch = self._make_data()
  File "C:\Users\niaza\TF-SimpleHuman\main\..\lib\tfflat\base.py", line 211, in _make_data
    data_load_thread.reset_state()
  File "C:\Users\niaza\TF-SimpleHuman\main\..\lib\tfflat\data_provider.py", line 371, in reset_state
    self.ds.reset_state()
  File "C:\Users\niaza\TF-SimpleHuman\main\..\lib\tfflat\data_provider.py", line 266, in reset_state
    self._reset_once()  # build processes
  File "C:\Users\niaza\TF-SimpleHuman\main\..\lib\tfflat\data_provider.py", line 236, in _reset_once
    self.socket.bind(pipename)
  File "zmq/backend/cython/socket.pyx", line 550, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
    raise ZMQError(errno)
zmq.error.ZMQError: Protocol not supported
MultiProcessMapDataZMQ successfully cleaned-up.
MultiProcessMapDataZMQ successfully cleaned-up.
