### ISSUE TITLE
Any model to create human detection json

### ISSUE THREAD

**Issue by IshrakHasin** [mks0601/TF-SimpleHumanPose#43]
Hi can you suggest any model to create human detection json. We are Technos data science Inc . from Japan.

**Comment by mks0601** [comment]
I used Detectron (https://github.com/facebookresearch/Detectron/blob/master/MODEL_ZOO.md)

**Comment by IshrakHasin** [comment]
Thank you very much

**Comment by IshrakHasin** [comment]
Can you please specify the tensorflow version you used to test?

**Comment by henbucuoshanghai** [comment]
how to get the human detection json???the mpii dataset has it????
it means get the pepole bbox from the imgs???

**Comment by mks0601** [comment]
It is provided in README
