### ISSUE TITLE
 __cudaRegisterFatBinaryEnd

### ISSUE THREAD

**Issue by IshrakHasin** [mks0601/TF-SimpleHumanPose#44]
I have not changed anything in the code and using the mentioned configurations described in the project. Finished the training. I am getting an error. Does anyone have any idea? The traceback is:
Traceback (most recent call last):
  File "test.py", line 24, in <module>
    from nms.nms import oks_nms
  File "/datadrive/common/Ishrak/Integral_Pose_estimation/TF-SimpleHumanPose/main/../lib/nms/nms.py", line 14, in <module>
    from .gpu_nms import gpu_nms
ImportError: /datadrive/common/Ishrak/Integral_Pose_estimation/TF-SimpleHumanPose/main/../lib/nms/gpu_nms.cpython-36m-x86_64-linux-gnu.so: undefined symbol: __cudaRegisterFatBinaryEnd

Best
Ishrak
Technos Data Science Engineering Inc, Tokyo

**Comment by mks0601** [comment]
Did you do this?
`Run cd ${POSE_ROOT}/lib and make to build NMS modules.`

**Comment by IshrakHasin** [comment]
Yes, I did. Still, the problem persists.

**Comment by mks0601** [comment]
I think that is something related with crush between NMS build version and your TF version. Could you re-build NMS?
