### ISSUE TITLE
Unable to visualize

### ISSUE THREAD

**Issue by IshrakHasin** [mks0601/TF-SimpleHumanPose#48]
I can't see the visualization in vis output after running the test. The test generated results and saved in result.pkl. I commented out from the  /lib/nms/nms.py:
from .gpu_nms import gpu_nms
to bypass CudaRegistarFatbinaryending error. Do you have any suggestions for why the vis folder empty?

**Comment by mks0601** [comment]
please check `vis = False` in `test.py`
