### ISSUE TITLE
resnet50？？？

### ISSUE THREAD

**Issue by henbucuoshanghai** [mks0601/TF-SimpleHumanPose#49]
blocks = [
        resnet_utils.Block('block1', bottleneck,
                           [(256, 64, 1)] * 2 + [(256, 64, 1)]),
        resnet_utils.Block('block2', bottleneck,
                           [(512, 128, 2)] + [(512, 128, 1)] * 3),
        resnet_utils.Block('block3', bottleneck,
                           [(1024, 256, 2)] + [(1024, 256, 1)] * 5),
        resnet_utils.Block('block4', bottleneck,
                           [(2048, 512, 2)] + [(2048, 512, 1)] * 2)
    ]   

blocks means resnet50？？？    but why compute net1234？？？
    resnet_features = [net, net2, net3, net4]
    return resnet_features

it means？？？

**Comment by mks0601** [comment]
<img width="769" alt="Screen Shot 2019-09-25 at 7 18 48 AM" src="https://user-images.githubusercontent.com/13601723/65596386-b94bff80-df64-11e9-971b-f5b6ff0d1772.png">

**Comment by mks0601** [comment]
What are those question marks? I cannot understand your question.

**Comment by henbucuoshanghai** [comment]
blocks means resnet50？？？ 
but why compute [net, net2, net3, net4]？？？

**Comment by mks0601** [comment]
I cannot understand your question. That is just pytorch official resnet code.

**Comment by henbucuoshanghai** [comment]
pytorch official resnet code?  tensorflow??

**Comment by mks0601** [comment]
Sorry, tensorflow

**Comment by henbucuoshanghai** [comment]
official resnet code. 
resnet v1?
but the official code is bad to understand,too complex to understand..
