### ISSUE TITLE
Input from OpenCV

### ISSUE THREAD

**Issue by jobim3d** [mks0601/TF-SimpleHumanPose#5]
Hi,
Can I get input stream from OpenCV?
Thank you very much.

**Comment by mks0601** [comment]
What do you mean by input stream?

**Comment by jobim3d** [comment]
Hi, I mean to get images from a webcam, a video or a still image.

**Comment by mks0601** [comment]
Sorry. That part is not implemented.

**Comment by thiranjayamunasinghe** [comment]
@paolomanchisi Hey, were you able to get the input stream from OpenCV?

**Comment by paolomanchisi** [comment]
@thiranjayamunasinghe  no sorry, I'm not working on this project anymore.
