### ISSUE TITLE
mpii to coco format

### ISSUE THREAD

**Issue by henbucuoshanghai** [mks0601/TF-SimpleHumanPose#50]
get the 12g mpii dataset,run the mpii2coco.py,
error

FileNotFoundError: [Errno 2] No such file or directory: '../images/015601864.jpg'

and I check the imags,it has no 015601864.jpg.
how to solve it

**Comment by sunahmin-lab** [comment]
how could you solve that problem?

**Comment by sanchitjain04** [comment]
What is the fix for this, i am facing same issue, although i have the file then also its giving above error
