### ISSUE TITLE
human detection json

### ISSUE THREAD

**Issue by henbucuoshanghai** [mks0601/TF-SimpleHumanPose#51]
how to get the human detection json???the mpii dataset has it????

it means get the pepole bbox from the imgs???

**Comment by henbucuoshanghai** [comment]
using a dnn approach?like faster rcnn??

**Comment by mks0601** [comment]
I haven't run human detection on MPII dataset, but you can run it using existing human detection models such as [mask-rcnn](https://github.com/facebookresearch/Detectron)

**Comment by henbucuoshanghai** [comment]
existing human detection models to detect the people in the mpii images????but how to get the new keypoints in the new imgs that detected by the mask-rcnn??

**Comment by mks0601** [comment]
Train TF-SimpleHumanPose on the MPII dataset.

**Comment by henbucuoshanghai** [comment]
i have the mpii dataset,and get train.json,test.json
i want to Train TF-SimpleHumanPose on the MPII dataset.
does i have to get the human detection json?how to get it
