### ISSUE TITLE
Regarding Training on Google cloud MLE.

### ISSUE THREAD

**Issue by Koteswara-ML** [mks0601/TF-SimpleHumanPose#56]
HI @mks0601 ,
How can we run this whole code in the Google cloud MLE ..? I have made sufficient changes in the whole code to make it run in the Cloud ML engine , but i was stuck at using 'pycocotools ' which will internally read the json file bucket.

`  File "/root/.local/lib/python3.5/site-packages/train/data/COCO/dataset.py", line 35, in load_train_data
    coco = COCO(self.train_annot_path)
  File "/usr/local/lib/python3.5/dist-packages/pycocotools/coco.py", line 84, in __init__
    dataset = json.load(open(annotation_file, 'r'))
FileNotFoundError: [Errno 2] No such file or directory: 'gs://pose_estimation_bucket/data/annotations/annotations/person_keypoints_train2017.json'
`
and this took me to this page...
[https://stackoverflow.com/a/42765641](url)

How can i make change in that library which is actually installed in cloud ML engine.
Thanks in advance...

**Comment by Koteswara-ML** [comment]
I solved it

**Comment by wingedrasengan927** [comment]
Great Work @Koteswara-ML. Amazing!
