### ISSUE TITLE
how to get the ap75,ap

### ISSUE THREAD

**Issue by henbucuoshanghai** [mks0601/TF-SimpleHumanPose#57]
AP | AP .5 | AP .75 | AP (M) | AP (L

**Comment by henbucuoshanghai** [comment]
ap  means oks??  where is the code to evaluate the test data???get the ap50,ap75???

**Comment by mks0601** [comment]
oks is metric how estimated 2d pose is close to the gt. ap is calculated from oks of whole data. To evaluate on test-dev, you should use codalab. See http://cocodataset.org/#keypoints-eval

**Comment by henbucuoshanghai** [comment]
in the papers.people always using the oks for coco,and pckh for mpii???&nbsp; &nbsp;isnt it???

**Comment by henbucuoshanghai** [comment]
where is the coco istance??crop it form the original images??? how to get the correspoding keypoints??

**Comment by mks0601** [comment]
please read the code and paper carefully.

**Comment by henbucuoshanghai** [comment]
but Results on MSCOCO 2017 dataset,it has ap75.ap50&nbsp; &nbsp;&nbsp;
&nbsp;The table below is APs on COCO val2017 set.

MethodsAPAP .5AP .75AP (M)AP (L)ARAR .5AR .75AR (M)AR (L)Download
256x192_resnet50
(this repo)70.488.677.867.076.976.293.083.071.982.4model
pose


how did you get it ???where is the code?&nbsp; thanks

**Comment by mks0601** [comment]
![스크린샷 2019-12-21 오전 1 27 57](https://user-images.githubusercontent.com/13601723/71268797-1f43f980-2391-11ea-8b16-9657869b142a.png)

This screenshot is what I'm seeing and I cannot understand what you are saying. Please ask questions in a more clear and specific way. Also, do not ask basic questions.
