### ISSUE TITLE
The code about test does not run successfully..........

### ISSUE THREAD

**Issue by YHDang** [mks0601/TF-SimpleHumanPose#58]
Hi. I downloaded the `human_detection.json`, and ran the `test.py` by `python test.py --gpu 0-1 --test_epoch 140`. But the code couldn't run successfully. The errors are as follows.
Traceback (most recent call last):
  File "test.py", line 256, in <module>
    test(int(args.test_epoch))
  **File "test.py", line 232, in test
    d.evaluation(result, annot, cfg.result_dir, cfg.testset)**
  File "/home/dyh/Sources/python/algorithm/TF-SimpleHumanPose-master/main/../d**ata/MPII/dataset.py**", line 90, in evaluation
    **savemat(result_path, mdict=result)**
  File "/home/dyh/anaconda3/envs/tensorflow/lib/python3.6/site-packages/scipy/io/matlab/mio.py", line 219, in savemat
    MW.put_variables(mdict)
  File "/home/dyh/anaconda3/envs/tensorflow/lib/python3.6/site-packages/scipy/io/matlab/mio5.py", line 834, in put_variables
    for name, var in mdict.items():
**AttributeError: 'list' object has no attribute 'items'**

How can I address this problem? I don't know if I downloaded the `human_detection.json` by mistakes. Could you provide the specific version?   
Thank you~

**Comment by mks0601** [comment]
The error comes from `savemat` from `../data/MPII/dataset.py`. It seems the savemat only accept a dict, not a list. However, in the `test.py`, `test_net` function returns list. It seems you should convert the list to dict format. I think this is not very hard, so you can try? I'll fix this problem soon. Thanks for reporting!

**Comment by YHDang** [comment]
Yeah! Thanks for your reply. I can do it

**Comment by mks0601** [comment]
Sorry, I only tested this code on PoseTrack and MSCOCO dataset, which are the most widely used datasets.

**Comment by YHDang** [comment]
OK, thanks. By the way, can I use the trained model to evaluate my own video ( I only need the visualization)?

**Comment by mks0601** [comment]
Of course. You can find the download link at README.
Here is the link.
https://drive.google.com/drive/folders/1DAyOVI-8q-gh1ooe6cMx6RA16GJ03Efn?usp=sharing

**Comment by YHDang** [comment]
Thanks very much. And I have one question. Where can I find the use of the optical flow in the code? 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Gyeongsik&nbsp;Moon"; 
发送时间: 2020年1月2日(星期四) 中午12:49
收件人: "mks0601/TF-SimpleHumanPose";
抄送: "YHDang"<769731469@qq.com>;"Author";
主题: Re: [mks0601/TF-SimpleHumanPose] The code about test does not run successfully.......... (#58)




Of course. You can find the download link at README.
 Here is the link.
 https://drive.google.com/drive/folders/1DAyOVI-8q-gh1ooe6cMx6RA16GJ03Efn?usp=sharing
 
&mdash;

**Comment by mks0601** [comment]
I did not implement the tracking part.
