### ISSUE TITLE
change image size to 384x288 and accuracy drops to 62AP? 

### ISSUE THREAD

**Issue by jackytu256** [mks0601/TF-SimpleHumanPose#6]
Hi, I just try to modify an input image size from 256x288 to 384x28, resulting in a 62 AP.  No idea why this happens.  The step I use is simply downloaded model and modify the parameter of the image size  in a config file

**Comment by mks0601** [comment]
You need to train another model for 384x288 input size. The provided model is trained for 256x192 input size.

**Comment by jackytu256** [comment]
Hi mks,
 Thanks for letting me know the main issue of why this stuff occurred. Training period takes 3 or 4 days to converge, utilized with 2 taitan XPs.

**Comment by mks0601** [comment]
Using more GPUs would short training schedule. If you encounter any problems, feel free to ask here.
