### ISSUE TITLE
tmp pickle file not found - used offered human detection file and model

### ISSUE THREAD

**Issue by Vhunon** [mks0601/TF-SimpleHumanPose#60]
Hello,

I used your 'human_detection.json' file from [here](https://drive.google.com/drive/folders/1zLtjDYPaXc-v7QQEIFgSjsTw6MyyXmSP?usp=sharing) and your model for the 140th epoch from [here](https://drive.google.com/drive/folders/1DAyOVI-8q-gh1ooe6cMx6RA16GJ03Efn?usp=sharing). The model was saved in the model-dump folder and the human detection file in ..`data/COCO/dets/`

However, I was not able to reproduce your code.

The error message:

> 02-10 22:54:38 Generating testing graph on 1 GPUs ...
> 02-10 22:54:40 Initialized model weights from /home/myName/TF-SimpleHumanPose/main/../output/model_dump/COCO/snapshot_140.ckpt ...
> 02-10 22:54:41 Current epoch is 140.
> Process Worker-1:
> Traceback (most recent call last):
>   File "/home/myName/anaconda3/envs/tf1/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
>     self.run()
>   File "/home/myName/TF-SimpleHumanPose/main/../lib/tfflat/mp_utils.py", line 34, in run
>     msg = self._func(self.id, *self.args, **self.kwargs)
>   File "test.py", line 225, in func
>     range = [ranges[gpu_id], ranges[gpu_id + 1]]
> IndexError: list index out of range
> Traceback (most recent call last):
>   File "test.py", line 256, in <module>
>     test(int(args.test_epoch))
>   File "test.py", line 229, in test
>     result = MultiGPUFunc.work()
>   File "/home/myName/TF-SimpleHumanPose/main/../lib/tfflat/mp_utils.py", line 82, in work
>     id, msg = load_pkl( 'tmp_result_{}'.format(self._proc_ids[i]) )
>   File "/home/myName/TF-SimpleHumanPose/main/../lib/tfflat/serialize.py", line 68, in load_pkl
>     with open('{}.pkl'.format(name), 'rb') as f:
> FileNotFoundError: [Errno 2] No such file or directory: 'tmp_result_0.pkl'

Which human_detection file is used?

**Comment by mks0601** [comment]
Please also check `dataset` and `testset` in `main/config.py`

**Comment by mks0601** [comment]
As described in README, `tmp_result_0.pkl` is temporal file and most of the reason of that error is wrong path or config.

**Comment by Vhunon** [comment]
Yes, dataset set to `COCO` and testset set to `val`

**Comment by mks0601** [comment]
What I mean is could you check your human detection file is for validation set?
Also, could you check the path of the human detection file is the same with `human_det_path` of `data/COCO/dataset.py`?

**Comment by Vhunon** [comment]
the human_det_path is set to `human_det_path = osp.join('..', 'data', dataset_name, 'dets', 'human_detection.json') # human detection result`.
For COCO I have `data/COCO/dets/human_detection.json` and this `human_detection.json` is yours provided in [here](https://drive.google.com/drive/folders/1zLtjDYPaXc-v7QQEIFgSjsTw6MyyXmSP?usp=sharing)

**Comment by mks0601** [comment]
Did you change the human detection name? because the original one has _val or _test_dev.jaon
Also, other paths such as annotations and images

**Comment by Vhunon** [comment]
Yes I changed it. So how do I test it then?

**Comment by mks0601** [comment]
python test.py --gpu 0 --test_epoch 140

**Comment by Vhunon** [comment]
What do you mean with

> Also, other paths such as annotations and images

Is there anything else that has to be changed?

**Comment by mks0601** [comment]
No just wanted to check you made soft links at `data/COCO/.`

**Comment by Vhunon** [comment]
Well any idea what is the issue then?

**Comment by mks0601** [comment]
Did you set GPU ids properly?

**Comment by Vhunon** [comment]
Yes of course

`python test.py --gpu 0 --test_epoch 140`

**Comment by mks0601** [comment]
I'm not sure... could you debug it by yourself? I have no problem when running this code

**Comment by Vhunon** [comment]
The `human_detection.json` [file](https://drive.google.com/drive/folders/1zLtjDYPaXc-v7QQEIFgSjsTw6MyyXmSP) must be placed in `data/COCO/dets/human_detection.json`
and the [model](https://drive.google.com/drive/folders/1DAyOVI-8q-gh1ooe6cMx6RA16GJ03Efn) being used is the snapshot model from your gdrive.
As for the configuration file, `dataset` and `testset` variable needs to be set `COCO` and `val` right?
Is there any other changes needed?

**Comment by mks0601** [comment]
I guess no. Most of this error comes from wrong path configuration or wrong human detection file. You can debug it by checking the human detection is loaded well or something

**Comment by Vhunon** [comment]
Since I am running this on one GPU, do I need to change the num of gpus in the config file?

**Comment by mks0601** [comment]
Hmm that maybe the reason.. I haven't run my code in single gpu environment. I remember some guys had similar problem in single gpu environment

**Comment by Vhunon** [comment]
Thank you I managed to get it run however I have a question. 
How do I generate my own `human_detection.json` file?

**Comment by mks0601** [comment]
I used https://github.com/facebookresearch/detectron2
