### ISSUE TITLE
Real time model

### ISSUE THREAD

**Issue by MozhganPourKeshavarz** [mks0601/TF-SimpleHumanPose#61]
I thank you so much for your contribution,
I'm going to train a human pose estimation model on my own dataset and use it in browser (server-less approach), 
at the first step, I just want to test a pre-trained model,
If I use this repo, I would grab a human detection model and then fed its result to your pre-trained model,
is it a good idea? do you think it can be work in real time with reasonable accuracy?
i would be appreciated if you could give me a hint,
thanks.

**Comment by mks0601** [comment]
Depends on which human detection model will you use, but I think it would be hard because this model is not lightweight for the purpose of server-less environment. You should search some mobilenet things

**Comment by thiranjayamunasinghe** [comment]
@MozhganPourKeshavarz Hey, Did you try this approach in a serverless environment. If so, did you get reasonable accuracy?
