### ISSUE TITLE
Training stuck with no verbose logs?

### ISSUE THREAD

**Issue by Ashwin-Ramesh2607** [mks0601/TF-SimpleHumanPose#65]
Hi @mks0601 , I started a training job for my custom dataset. I set up the directories and data as per the repo. However, when I start training it is stuck "07-12 06:53:23 Start training ..." with this comment
![Screenshot from 2020-07-12 12-34-32](https://user-images.githubusercontent.com/51472801/87240995-371dc080-c43c-11ea-81c4-4022529d99a6.png)
Is this correct? Or am I going wrong somewhere

**Comment by Ashwin-Ramesh2607** [comment]
Sorry, there were some path issues related to my dataset. Resolved now

**Comment by GK4444** [comment]
I am having the same issue. What paths did u change?

**Comment by Ashwin-Ramesh2607** [comment]
If your custom dataset has annotations in the COCO format, then you should ensure that your dataset conforms to the directory structure here.

https://github.com/mks0601/TF-SimpleHumanPose/blob/master/data/COCO/dataset.py#L27-L32

**Comment by GK4444** [comment]
yes, i maintained the same directory structure still the training is stuck. Also which tensorflow version were u using coz tf2 throws contrib error.
