### ISSUE TITLE
where to place mpii_human_pose_v1_u12_1

### ISSUE THREAD

**Issue by AkshayMalavade** [mks0601/TF-SimpleHumanPose#68]
i placed mpii_human_pose_v1_u12_1 in tool directory and ran the code. it gives me an error no such directory found. aslo you said  to human_detection.json is in README section , I don't find it can you please give me a link please

**Comment by mks0601** [comment]
You shoud put the json file at [here](https://github.com/mks0601/TF-SimpleHumanPose/blob/5e958ae7832b282cb7134b312091a1b5076e4e89/tool/mpii2coco.py#L25).
You can find the human_detection.json in README.

**Comment by AkshayMalavade** [comment]
No I checked all files in your repo , I didn't find human_detection.json file

**Comment by AkshayMalavade** [comment]
> You shoud put the json file at [here](https://github.com/mks0601/TF-SimpleHumanPose/blob/5e958ae7832b282cb7134b312091a1b5076e4e89/tool/mpii2coco.py#L25).
> You can find the human_detection.json in README.
No no. I meant it gives me error when I run mpii2coco.py it says no directory for annotations found. How do I modify code so it can access that mpii annotation directory. And human_detection.json is not there in read me section only the link to coco web is available. I don't know how to make my own .json file. Please send the file.

**Comment by AkshayMalavade** [comment]
https://github.com/mks0601/TF-SimpleHumanPose/blob/5e958ae7832b282cb7134b312091a1b5076e4e89/tool/mpii2coco.py#L24

 In this line should it be .mat ??

**Comment by mks0601** [comment]
mat file dir: https://github.com/mks0601/TF-SimpleHumanPose/blob/5e958ae7832b282cb7134b312091a1b5076e4e89/tool/mpii2coco.py#L24
human detection: https://github.com/mks0601/TF-SimpleHumanPose#results-on-mscoco-2017-dataset

**Comment by AkshayMalavade** [comment]
what about image_info_test-dev2017.json file in coco ??? is this and human_detection_test-dev2017 same?? should i just rename it?
