### ISSUE TITLE
Convert mpii to coco format 

### ISSUE THREAD

**Issue by CVStack** [mks0601/TF-SimpleHumanPose#82]
Hi. Thank you for sharing the code.

I tried to convert mpii dataset to coco format with your code 'tools/mpii2coco.py'. 

But the annotations of 'test.json' generated by this code is not existed. 

How can i get the annotation of 'test'.json'?

thank you again for sharing your code.

**Comment by mks0601** [comment]
MPII dataset is used only for the training purpose.

**Comment by CVStack** [comment]
Oh I got it! Thank you!
