### ISSUE TITLE
OOM while training

### ISSUE THREAD

**Issue by jackytu256** [mks0601/TF-SimpleHumanPose#9]
Hi mks,

First of all, thanks for making this such an amazing implementation of SHP; however, I encounter an OOM issue while training the model that The more time I utilize to train the model the larger memory is occupied. The way I fixed is to simply add a "graph.finalize" before iter. 

Please just let me know If you need more info.
Thanks

**Comment by mks0601** [comment]
Hi, thanks for your info. I haven't encounter that problem, however I'll add this at my README.
